#!/bin/sh

print_patch()
{
    author=`quilt header $1 | grep -e '^Author' | cut -d : -f 2`
    patch_name=`echo $1 | sed 's/[^_]*_\(.*\)/\1/'`
    patch_description=`quilt header $1 | grep -e '^Description' | cut -d : -f 2`
    echo $patch_name:
    if [ ! -z "$author" ] ; then
       echo "    $author"
       echo
    fi
    if [ ! -z "$patch_description" ] ; then
        echo $patch_description | fmt | sed 's/\(.*\)/    \1/'
    fi
    echo
}

echo "Patches applied to vanilla vdr sources"
echo "--------------------------------------"
echo

patches_applied=`quilt series |  sed 's/\(.*\)\.patch/\1/'`
for patch in $patches_applied ; do
    print_patch $patch
done

echo
echo "Patches available in source package, but not active"
echo "---------------------------------------------------"
echo

patches_available=`find debian/patches -name *.patch -printf "%f\n" | sed 's/\(.*\)\.patch/\1/'`
for patch in $patches_available ; do
    is_applied="no"

    for applied_patch in $patches_applied ; do
        if [ $applied_patch = $patch ] ; then
            is_applied="yes"
            break
        fi
    done
    
    if [ $is_applied = "no" ] ; then
        print_patch $patch
    fi
done
