#!/usr/bin/env bash
#
# This file is called by /etc/init.d/vdr and by vdr.service
#
# Merges single <cmdtype>.<name>.conf files into one <cmdtype>.conf
# in alphabetical order
#

source /usr/lib/vdr/config-loader.sh

f_writewarning() {
cat > "$2" <<EOF
# This file is automatically generated by the vdr init-script. You can
# define custom commands in /etc/vdr/command-hooks/$1.custom.conf
# (see /usr/share/doc/vdr/README.Debian.gz).

EOF
}

cmdtype="$1"
cmdfile="/var/cache/vdr/${cmdtype}.conf"

f_writewarning "$cmdtype" "$cmdfile"

shopt -s nullglob  # In case of no matches

# Only match '<cmdtype>.<name>.conf'
cat "${CMDHOOKSDIR}/${cmdtype}".*.conf > "$cmdfile"
