.TH "svdrpsend" "1" "" "Tobias Grimm" ""
.SH "NAME"
.LP 
svdrpsend \- Sends commands to VDR
.SH "DESCRIPTION"
.LP 
This program sends commands to VDR and displays the result. A list of available commands can be shown by sending the HELP command.
.SH "SYNTAX"
.LP 
svdrpsend [\fIoptions\fP] \fIcommand\fP
.SH "OPTIONS"
.LP 
.TP 
\fB\-d\fR <\fIhostname\fP>
Accesses the VDR at the specified <\fIhostname\fP> (default is localhost).
.TP 
\fB\-p\fR <\fIport\fP>
Uses the SVDRP port number <\fIport\fP> (default is 6419).
.SH "EXAMPLES"
.LP 
To request the available commands from the VDR running on the local host:
.LP 
svdrpsend HELP
.SH "FILES"
.LP 
\fI/etc/vdr/svdrphosts.conf\fP 
.SH "AUTHORS"
.LP 
This man-page has been written by Tobias Grimm <tg@e\-tobi.net>
.PP
Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 any
later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public
License can be found in /usr/share/common\-licenses/GPL.
.SH "SEE ALSO"
.LP 
vdr(1) vdr(5)
