usr/include
usr/lib/pkgconfig/vdr.pc

Make.config                                 usr/include/vdr/
debian/plugins.mk                           usr/include/vdr/

PLUGINS/src/dvbhddevice/dvbhdffdevice.h     usr/include/vdr/plugins/dvbhddevice/
PLUGINS/src/dvbhddevice/hdffcmd.h           usr/include/vdr/plugins/dvbhddevice/
PLUGINS/src/dvbhddevice/libhdffcmd/*.h      usr/include/vdr/plugins/dvbhddevice/libhdffcmd/

PLUGINS/src/dvbsddevice/dvbsdffdevice.h     usr/include/vdr/plugins/dvbsddevice/

debian/debianize-vdrplugin      usr/bin/

debian/plugin-template/         usr/share/vdr-dev/
debian/abi-version              usr/share/vdr-dev/

debian/dh-addon-vdrplugin/vdrplugin.pm               usr/share/perl5/Debian/Debhelper/Sequence/
debian/dh-addon-vdrplugin/preinst-vdrplugin*         usr/share/debhelper/autoscripts/
debian/dh-addon-vdrplugin/postinst-vdrplugin*        usr/share/debhelper/autoscripts/
debian/dh-addon-vdrplugin/postrm-vdrplugin*          usr/share/debhelper/autoscripts/
debian/dh-addon-vdrplugin/dh_vdrplugin_depends       usr/bin/
debian/dh-addon-vdrplugin/dh_vdrplugin_enable        usr/bin/
debian/dh-addon-vdrplugin/dh_vdrplugin_migrate       usr/bin/
