*.h                             usr/include/vdr/

libsi/*.h                       usr/include/vdr/libsi/

debian/debianize-vdrplugin      usr/bin/
debian/plugin-template/         usr/share/vdr-dev/

vdr-newplugin                   usr/bin/

debian/lintian/vdr-dev          usr/share/lintian/overrides/

debian/patchlevel.sh            usr/lib/vdr-dev/
debian/patchlevel.sh            usr/lib/vdr-dev/
