usr/lib/vdr/libvdr-hello.so.*           usr/lib/vdr/plugins/
usr/lib/vdr/libvdr-osddemo.so.*         usr/lib/vdr/plugins/
usr/lib/vdr/libvdr-svccli.so.*          usr/lib/vdr/plugins/
usr/lib/vdr/libvdr-svcsvr.so.*          usr/lib/vdr/plugins/
usr/lib/vdr/libvdr-skincurses.so.*      usr/lib/vdr/plugins/
usr/lib/vdr/libvdr-status.so.*          usr/lib/vdr/plugins/
usr/lib/vdr/libvdr-svdrpdemo.so.*       usr/lib/vdr/plugins/
usr/lib/vdr/libvdr-pictures.so.*        usr/lib/vdr/plugins/
