usr/include
usr/lib/pkgconfig/vdr.pc

debian/debianize-vdrplugin      usr/bin/

debian/plugin-template/         usr/share/vdr-dev/
debian/dependencies.sh          usr/share/vdr-dev/
debian/abi-version              usr/share/vdr-dev/

debian/dh-addon-vdrplugin/vdrplugin.pm               /usr/share/perl5/Debian/Debhelper/Sequence/
debian/dh-addon-vdrplugin/postinst-vdrplugin-enable  /usr/share/debhelper/autoscripts/
debian/dh-addon-vdrplugin/postrm-vdrplugin-enable    /usr/share/debhelper/autoscripts/
debian/dh-addon-vdrplugin/dh_vdrplugin_depends       /usr/bin/
debian/dh-addon-vdrplugin/dh_vdrplugin_enable        /usr/bin/
