#!/bin/sh

## NAME
##   vdrdbg-buildpackage - builds a VDR plugin for debugging
## 
## SYNOPSIS
##   vdrdbg-buildpackage [dpkg-puildpackage-options]
## 
## DESCRIPTION
##   vdrdbg-buildpackage is a small wrapper for dpkg-buildpackage, which
##   sets all options needed to compile a VDR plugin for debugging.
## 
## OPTIONS
##   -h This help
## 
##   All dpkg-buildpackage options are available for vdrdbg-buildpackage
##   as well.
## 
## SEE ALSO
##   dpkg-buildpackage (1)
## 
## AUTHOR
##   This manual page was written by Tobias Grimm <tg@e-tobi.net>
## 
### txt2man -s 1 -t VDRDBG-BUILDPACKAGE -v "Create VDR dbeug plugin package"

usage()
{
    local HELPCOMMENTPATTERN="^## "
    cat "$0" | grep "$HELPCOMMENTPATTERN" | sed "s/$HELPCOMMENTPATTERN//"
}

while getopts :h opt
do
    case $opt in
        h)
            usage
            exit
            ;;
    esac
done

export DEB_BUILD_OPTIONS="noopt nostrip $DEB_BUILD_OPTIONS"
export VDRDEBUG=yes
dpkg-buildpackage $*
