#!/bin/sh
#
# c't-VDR Memory Leak Tester
#

. /usr/lib/vdr/config-loader.sh
. /usr/lib/vdr/commands-loader.sh

mergecommands "commands"
mergecommands "reccmds"

/etc/init.d/vdr stop

LANG=C LD_LIBRARY_PATH="/usr/lib/debug;$LD_LIBRARY_PATH" \
   valgrind --tool=memcheck --leak-check=yes --num-callers=20 \
   --suppressions=/usr/share/vdr/valgrind.supp \
   /usr/bin/vdr-dbg -v $VIDEO_DIR -c $CFG_DIR -L $PLUGIN_DIR  -r $REC_CMD \
   -E $EPG_FILE -g /tmp $OPTIONS --port $SVDRP_PORT --lirc \
   "$@" 2>/tmp/memleaktest.log

/etc/init.d/vdr restart
