#! /usr/bin/perl -w

=head1 NAME

dh_vdrplugin_depends - calculates vdr dependencies

=cut

use strict;
use Debian::Debhelper::Dh_Lib;

=head1 SYNOPSIS

B<dh_vdrplugin_depends> [S<I<debhelper options>>]

=head1 DESCRIPTION

dh_vdrplugin_depends is a debhelper program that is responsible for generating the
${vdr:Depends} substvars substitution for a vdr plugin package.

Each vdr-plugin is required to have a ${vdr:Depends} substvar listed in its
Depends line in debian/control. 

=head1 EXAMPLES

dh_vdrplugin_depends is usually called indirectly in a rules file via the dh command.

	%:
		dh --with vdrplugin $@

It can also be called directly, prior to calling dh_gencontrol.

=head1 CONFORMS TO

Debian policy, version 3.8.1

=cut

init ();

no locale;

open(my $abiversion_file, "</usr/share/vdr-dev/abi-version") or die "Could not read VDR's ABI version dependency";
my @abiversion = <$abiversion_file>;
close($abiversion_file);

verbose_print("Setting vdr:Depends=@abiversion");

foreach my $package (@{$dh{DOPACKAGES}}) {
  delsubstvar($package, "vdr:Depends");
  addsubstvar($package, "vdr:Depends", @abiversion);
}

=head1 SEE ALSO

L<debhelper(7)>

This program is not a part of debhelper.

=head1 AUTHOR

Tobias Grimm <tobias.grimm@e-tobi.net>

=cut
